---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-curvebs-nodeplugin
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-curvebs-nodeplugin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.curvebs.csi.netease.com/aggregate-to-csi-curvebs-nodeplugin: "true"
rules: []

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-curvebs-nodeplugin-rules
  labels:
    rbac.curvebs.csi.netease.com/aggregate-to-csi-curvebs-nodeplugin: "true"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-curvebs-nodeplugin
subjects:
- kind: ServiceAccount
  name: csi-curvebs-nodeplugin
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-curvebs-nodeplugin
  apiGroup: rbac.authorization.k8s.io
