driverName: curvebs.csi.netease.com

# node plugin variables
nodeplugin:
  debug:
    enabled: true
    port: 9595

  logToFile:
    enabled: true
    hostDir: /var/log/curvebs-csi-node

  plugin:
    image: harbor.cloud.netease.com/qzprod-k8s/k8scsi/curve-csi:v2.0.0
    # add resources limit
    resources: {}

  registrar:
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
    # add resources limit
    resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

# controller plugin variables
controllerplugin:
  replicas: 2

  snapshotServer: http://127.0.0.1:5555

  debug:
    enabled: true
    port: 9696

  logToFile:
    enabled: true
    hostDir: /var/log/curvebs-csi-controller

  plugin:
    image: harbor.cloud.netease.com/qzprod-k8s/k8scsi/curve-csi:v2.0.0
    # add resources limit
    resources: {}

  provisioner:
    image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
    # add resources limit
    resources: {}

  attacher:
    image: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
    # add resources limit
    resources: {}
  
  resizer:
    image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
    # add resources limit
    resources: {}
  
  snapshotter:
    image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
    # add resources limit
    resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
