---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: curvebs-pvc-clone
spec:
  storageClassName: curvebs
  dataSource:
    name: curvebs-test-pvc
    kind: PersistentVolumeClaim
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi