---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: curvebs-pvc-restore
spec:
  storageClassName: curvebs
  dataSource:
    name: curvebs-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi